# Generated by Django 2.2 on 2022-10-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='matt', max_length=100),
        ),
    ]
