# Generated by Django 2.2 on 2022-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikingapp', '0005_auto_20221029_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('public', 'Public'), ('public', 'Private')], max_length=200),
        ),
    ]
