# Generated by Django 2.2 on 2022-10-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="zipcode",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
