# Generated by Django 2.2 on 2022-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0002_event_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="state",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
