# Generated by Django 2.2 on 2022-11-21 20:35

import bikingapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0002_auto_20221121_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="default/user.jpg",
                upload_to=bikingapp.models.CustomUser.image_upload_to,
            ),
        ),
    ]
