# Generated by Django 2.2 on 2022-12-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0006_auto_20221203_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="latitude",
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="issue",
            name="longitude",
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
