# Generated by Django 2.2 on 2022-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikingapp', '0006_auto_20221029_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='Public', max_length=200),
        ),
    ]
