# Generated by Django 2.2 on 2022-12-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0007_auto_20221203_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="latitude",
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name="issue",
            name="longitude",
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
    ]
