# Generated by Django 2.2 on 2022-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0007_auto_20221029_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="borough",
            field=models.CharField(
                choices=[
                    ("manhattan", "Manhattan"),
                    ("queens", "Queens"),
                    ("bronx", "Bronx"),
                    ("staten island", "Staten Island"),
                    ("brooklyn", "Brooklyn"),
                ],
                default="Manhattan",
                max_length=20,
            ),
        ),
    ]
