# Generated by Django 2.2 on 2022-12-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikingapp', '0005_discforumcomment'),
        ('bikingapp', '0008_auto_20221203_1756'),
    ]

    operations = [
    ]
