# Generated by Django 4.1.2 on 2022-11-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikingapp', '0011_rename_content_comment_body_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
