# Generated by Django 2.2 on 2022-11-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0013_auto_20221112_0012"),
        ("bikingapp", "0012_auto_20221113_0058"),
    ]

    operations = []
