# Generated by Django 2.2 on 2022-11-14 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bikingapp", "0014_merge_20221114_1050"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="time",
            new_name="time_end",
        ),
        migrations.AddField(
            model_name="workout",
            name="time_start",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
